### ISSUE TITLE
BUG-000092425 -> GeoForm app hangs after the second or third submission in one browser session.

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/geoform-template-js#486]
Matt and Team - I was able to replicate this issue with Jacob from Esri Support today. 

If you enter more than one or two submissions without refreshing the page, it hangs indefinitely. The workaround for now is to just close and reopen the app.

Here is the app support created to replicate the issue: http://www.arcgis.com/apps/GeoForm/index.html?appid=97fc136695da4bfe8701a8669327299b

I know that support will log this and you will get notified, but I wanted to bring it to your attention right away since it is a pretty critical bug. There are many use-cases where the User would want to make multiple submissions in one sitting.

Here is the User I am working with that is impacted by this bug, the Mountain Rescue Association.
ArcGIS Online Account: http://msar.maps.arcgis.com/home/
Video: https://www.youtube.com/playlist?list=PLcpnLVkiGtjkDGELipKhmOZ9K9OxvuZax

**Comment by driskull** [comment]
I'm looking into it but It likely won't be fixed for a while. It has to do with the offline features manager.

**Comment by driskull** [comment]
Error example: 

![screen shot 2015-11-23 at 4 32 09 pm](https://cloud.githubusercontent.com/assets/1231455/11354349/aa73c4cc-91ff-11e5-80cb-e20ef8a91127.png)


cc @kellyhutchins @andygup

**Comment by pjdohertygis** [comment]
Would disabling offline features on the service and app be a workaround?

**Comment by andygup** [comment]
I'll take a look first thing this a.m. when I get into work. 

@driskull Last time I saw a similar error it was due to dirty data. Each feature had duplicate objectid properties.

**Comment by andygup** [comment]
@driskull Let's chat when you get in. I found at least two problems right off the bat with the tech support [GeoForm_Defect app](http://www.arcgis.com/apps/GeoForm/index.html?appid=97fc136695da4bfe8701a8669327299b#top). 

1) The feature layer isn't being extended correctly with offlineFeaturesManager. I'm able to determine this from the following error in `offlineFeaturesManager.pendingEditsCount()` immediately after filling out the GeoForm_Defect app and hitting the submit button. See screen shots below.

2) This error sets up the library for failure because the GeoForm apps thinks there are pending edits when, in fact, there are none. This forcing the offlineFeaturesManager library to attempt to go online before it has initialized correctly and causes a cascade failure.


![image](https://cloud.githubusercontent.com/assets/510440/11371799/8eb8ad0a-9287-11e5-9239-bc30225f7e9d.png)

![image](https://cloud.githubusercontent.com/assets/510440/11371778/7c162286-9287-11e5-9225-34858df4fa5c.png)

**Comment by driskull** [comment]
hey @andygup can we edit this gist to get it working correctly. Most of it is in the `initEditor` function. I think it should be pretty straight forward.

https://gist.github.com/driskull/bf7216ca8f49003b20cd

I also had a couple other questions:

1. Do we still need to pass graphic to editstore? `this.editStore = new O.esri.Edit.EditStore(Graphic);`?
2. Is this still the correct way to init attachments? `this.offlineFeaturesManager.initAttachments();`?

**Comment by andygup** [comment]
>>an we edit this gist to get it working correctly. Most of it is in the initEditor

Is initEditor being called by the main application after the map's `layers-add-result` event?

I also recommend checking for `success` in the [`extend(function(success,error){ . . . })`](https://gist.github.com/driskull/bf7216ca8f49003b20cd#file-offline-js-L111) callback and handling failures appropriately. At the moment the app will continue running whether the `extend` is successful or not. 

>>Do we still need to pass graphic to editstore? 

Nope. That will mess things up in the version you are using (v2.15). I recommend deleting [line 99](https://gist.github.com/driskull/bf7216ca8f49003b20cd#file-offline-js-L99).

>>Is this still the correct way to init attachments? `this.offlineFeaturesManager.initAttachments();`

I'd recommend using `offlineFeaturesManager.initAttachments(callback);` The callback returns `true` if the database successfully initialized and `false` lets you handle initialization failure appropriately. 

For future reference, here's the link to the How to Use doc: https://github.com/Esri/offline-editor-js/blob/master/doc/howtouseofmadvancedlibrary.md

**Comment by andygup** [comment]
@driskull Also just an FYI, I released v3 of the offline library. https://github.com/Esri/offline-editor-js/blob/master/CHANGELOG.md

**Comment by driskull** [comment]
@andygup initEditor is being called after the layer is loaded. Does it need to be after layers-add-result?

**Comment by andygup** [comment]
Yes, use the `layers-add-result` event. The layer is `undefined` by the time your code calls `extend()`. 

Once you change the event, set a break point at Line 375 in offline-edit-min.js as shown in my screenshot above. If variable `a` is `undefined` (a == featureLayer) then something is still not right in the initialization sequence.

**Comment by driskull** [comment]
The issue was that extend was getting called twice.

@kellyhutchins it's too late to patch right?

**Comment by kellyhutchins** [comment]
@driskull  yes its my understanding that its too late.

**Comment by driskull** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1231455/11378764/b4504b30-92a1-11e5-80e4-df884370b528.gif)

**Comment by andygup** [comment]
var status = { condition: "oopsie" }

:no_good:

**Comment by pjdohertygis** [comment]
:(

On Tue, Nov 24, 2015 at 2:51 PM, Matt Driscoll <notifications@github.com>
wrote:

> [image: giphy]
> <https://cloud.githubusercontent.com/assets/1231455/11378764/b4504b30-92a1-11e5-80e4-df884370b528.gif>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/geoform-template-js/issues/486#issuecomment-159386559>
> .
>



-- 

Paul J. Doherty, PhD | Senior Project Manager

National Alliance for Public Safety GIS Foundation

Tel. (202) 895-1711 | Email pdoherty@publicsafetygis.org

www.napsgfoundation.org | @napsgfoundation
<https://twitter.com/napsgfoundation> | USNG 18S UJ 19268 14427
<http://arcg.is/1NLghBh>

**Comment by pjdohertygis** [comment]
Thank you all for your help! @andygup @driskull If you need help with testing via GitHub io let us know. The MRA is pretty bummed about the bug because it will slow them down and confuse the members - but happy we found the cause.

**Comment by tchristo** [comment]
I'm having the same issue. Works after 1st submission, then hangs on 2nd submission. This GeoForm (http://wdfw.maps.arcgis.com/apps/GeoForm/index.html?appid=7479270999664006bba6b335578a5cb4#top ) has been up for 2 months now and am only just having problem now, so I'm assuming it was part of the last AGOL updates? I'm not sure what the response of "It has to do with the offline features manager." means and if there is some workaround I can use for this. The data is coming from our own ArcGIS Server not AGOL hosted layers. The feature service isn't published to be used offline, so I don't have "synch" turned on. 

So is the only solution, until the next update in 3 months, to tell people to "refresh after each submission"? I was just about to roll out another GeoForm but this might have to wait until this issue is resolved.

**Comment by amarinelli** [comment]
@tchristo this is the exact scenario we are facing - noticed the issue after the most recent update.  We are also using ArcGIS Server services (secured) without the Sync capability.

I could be wrong but if you have access to a web server to host the app yourself (instead of using the ArcGIS Online hosted version), I believe this commit c8a88cb3c5e8cbf2c22c6ce3291d805992aa308f in the [development branch](https://github.com/Esri/geoform-template-js/tree/development) contains the fix - _I have not personally tested_.

**Comment by tchristo** [comment]
@amarinelli, thanks for indicating the workaround, unfortunately, even though we are using AGS to publish services, we are still relying on AGOL to publish our web maps/apps. I would like to switch to Portal to host these apps (for this and many other reasons) but our org has not been willing to make this switch yet

**Comment by pjdohertygis** [comment]
How is it going? Think this will be fixed for the next release? There are a lot of people asking me when this will be fixed. Anything I can do to help?

**Comment by driskull** [comment]
this was already fixed

**Comment by driskull** [comment]
yeah it should be

**Comment by pjdohertygis** [comment]
Excellent just tested and works without issue. Great work and rapid response - way to go team!

**Comment by craygo69** [comment]
I am still getting the error when trying to submit another entry. I just downloaded the latest template.
When I submit the first entry. I still get the TypeError
![geoform_submit_1_console](https://cloud.githubusercontent.com/assets/16541368/12091933/1e820250-b2c8-11e5-8a29-abdbbf87e023.jpg)

When I submit the second entry I get this error
![geoform_submit_2_console](https://cloud.githubusercontent.com/assets/16541368/12091957/3db69ac8-b2c8-11e5-90c7-c14ce964c749.jpg)

Also I am using Portal and hosting my own feature services.

Ray

**Comment by driskull** [comment]
@craygo69 try downloading it again. I updated the master branch.

**Comment by craygo69** [comment]
Still same error. Not sure if I am going to the right place to download the updated version. I have been clicking on geoform-template-js up top then download the zip file. I replaced all files in my directory then changed the config default.js.

Am I doing something wrong??

**Comment by andygup** [comment]
@craygo69 Can you send the stack trace for that error? In your console log, there is down arrow next to the message `Type Error: a is not a function`. Expand that and then send us a new screenshot of just the stack trace. I want to confirm it's the exact same error.

**Comment by craygo69** [comment]
Matt and Andy,
While trying to debug I deleted all files, cleared my cache and did a complete reload of the pages and the error is gone. All seems well right now. Entries are going in and there are no errors in the console.

Thanks for the help and sorry to open up a closed bug.

Ray

**Comment by driskull** [comment]
no worries :+1:
